### ISSUE TITLE
not gonna give you up!

### ISSUE THREAD

**Issue by geovedi** [svmihar/koinworks-complaint#1]
your repo piqued my curiosity! now that i'm capable to do something on behalf of koinworks: has your issue been solved?

also your approach on how to collect, organise and present the issue is somehow align to what i have in mind: are you interested to join with us at koinworks?

-j
gardien de la monnaie du pape, koinworks

**Comment by svmihar** [comment]
i don't think so, i'm casting spells somewhere else, but i gladly teach your interns if it makes us both happy and better experience for your users, my bad for the troll you can email me [here](mailto:svmihar@gmail.com?subject=[GitHub]%20Koinworks%20)

regards, 
svmihar
